// Bridge between the UI (renderer) and main process. Keep this thin.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  listModels: () => ipcRenderer.invoke('models:list'),
  getModelRecommendations: (mode) => ipcRenderer.invoke('models:recommendations', { mode }),
  installModel: (model) => ipcRenderer.invoke('models:install', { model }),
  onModelInstallProgress: (cb) => {
    const handler = (_event, progress) => cb(progress);
    ipcRenderer.on('models:install-progress', handler);
    return () => ipcRenderer.removeListener('models:install-progress', handler);
  },
  autoRouteModel: (options) => ipcRenderer.invoke('models:autoRoute', options),
  pickCwd: () => ipcRenderer.invoke('cwd:pick'),
  dirExists: (p) => ipcRenderer.invoke('dir:exists', p),
  send: (payload) => ipcRenderer.invoke('chat:send', payload),
  stop: () => ipcRenderer.send('chat:stop'),
  reset: () => ipcRenderer.invoke('chat:reset'),
  getConversation: () => ipcRenderer.invoke('chat:get'),
  loadConversation: (msgs, model, runMetrics, contextState, view) => ipcRenderer.invoke('chat:load', msgs, model, runMetrics, contextState, view),
  contextState: () => ipcRenderer.invoke('context:state'),
  contextControl: (payload) => ipcRenderer.invoke('context:control', payload),
  gitStatus: (cwd) => ipcRenderer.invoke('git:status', cwd),
  gitDiff: (cwd) => ipcRenderer.invoke('git:diff', cwd),
  gitGraph: (cwd) => ipcRenderer.invoke('git:graph', cwd),
  gitCommit: (cwd, message) => ipcRenderer.invoke('git:commit', cwd, message),
  memoryGet: (cwd) => ipcRenderer.invoke('memory:get', cwd),
  ledgerGet: () => ipcRenderer.invoke('ledger:get'),
  autonomyState: () => ipcRenderer.invoke('autonomy:state'),
  autonomySet: (id) => ipcRenderer.invoke('autonomy:set', id),
  autonomyOpenConfig: () => ipcRenderer.invoke('autonomy:openConfig'),
  agentRun: (payload) => ipcRenderer.invoke('agent:run', payload),
  triggersState: (cwd) => ipcRenderer.invoke('triggers:state', cwd),
  triggersOpenConfig: () => ipcRenderer.invoke('triggers:openConfig'),
  triggersRun: (id) => ipcRenderer.invoke('triggers:run', id),
  triggersEnableProject: (cwd, id) => ipcRenderer.invoke('triggers:enableProject', { cwd, id }),
  triggersDisableProject: (cwd, id) => ipcRenderer.invoke('triggers:disableProject', { cwd, id }),
  pendingList: () => ipcRenderer.invoke('pending:list'),
  pendingResolve: (runId, index, approved) => ipcRenderer.invoke('pending:resolve', { runId, index, approved }),
  pendingResume: (runId) => ipcRenderer.invoke('pending:resume', runId),
  memoryMove: (cwd) => ipcRenderer.invoke('memory:move', cwd),
  workspaceState: (cwd) => ipcRenderer.invoke('workspace:state', cwd),
  workspaceInit: (cwd) => ipcRenderer.invoke('workspace:init', cwd),
  autonomySuggestions: () => ipcRenderer.invoke('autonomy:suggestions'),
  autonomyPromote: (policyId, toolName) => ipcRenderer.invoke('autonomy:promote', { policyId, toolName }),
  mcpTrustAccept: (server) => ipcRenderer.invoke('mcp:trustAccept', server),
  discordState: () => ipcRenderer.invoke('discord:state'),
  discordOpenConfig: () => ipcRenderer.invoke('discord:openConfig'),
  daemonStatus: () => ipcRenderer.invoke('daemon:status'),
  daemonInstall: () => ipcRenderer.invoke('daemon:install'),
  daemonStart: () => ipcRenderer.invoke('daemon:start'),
  daemonStop: () => ipcRenderer.invoke('daemon:stop'),
  daemonUninstall: () => ipcRenderer.invoke('daemon:uninstall'),
  usageGet: () => ipcRenderer.invoke('usage:get'),
  mcpStatus: () => ipcRenderer.invoke('mcp:status'),
  mcpToggle: (name, on) => ipcRenderer.invoke('mcp:toggle', name, on),
  mcpOpenConfig: () => ipcRenderer.invoke('mcp:openConfig'),
  contextInspect: (payload) => ipcRenderer.invoke('context:inspect', payload),
  isDev: () => ipcRenderer.invoke('app:isDev'),
  openOllamaSite: () => ipcRenderer.invoke('app:openOllamaSite'),
  undoCheckpoint: (cwd) => ipcRenderer.invoke('checkpoint:undo', cwd),
  onCheckpointState: (cb) => ipcRenderer.on('checkpoint:state', (_e, d) => cb(d)),
  onRunReport: (cb) => ipcRenderer.on('run:report', (_e, d) => cb(d)),
  onRunDecisions: (cb) => ipcRenderer.on('run:decisions', (_e, d) => cb(d)),
  onExternalRun: (cb) => ipcRenderer.on('run:external', (_e, d) => cb(d)),
  getVersion: () => ipcRenderer.invoke('app:getVersion'),
  updateState: () => ipcRenderer.invoke('updates:state'),
  checkForUpdates: () => ipcRenderer.invoke('updates:check'),
  installUpdate: () => ipcRenderer.invoke('updates:install'),
  onUpdateState: (cb) => {
    const handler = (_event, state) => cb(state);
    ipcRenderer.on('updates:state', handler);
    return () => ipcRenderer.removeListener('updates:state', handler);
  },
  providerState: () => ipcRenderer.invoke('provider:state'),
  providerSetKey: (value) => ipcRenderer.invoke('provider:setKey', value),
  settingsGet: () => ipcRenderer.invoke('settings:get'),
  settingsSave: (settings) => ipcRenderer.invoke('settings:save', settings),
  settingsTestEndpoint: (endpoint) => ipcRenderer.invoke('settings:testEndpoint', endpoint),
  compact: (payload) => ipcRenderer.invoke('chat:compact', payload),
  loop: (payload = {}) => ipcRenderer.invoke('chat:loop', payload),
  plan: (payload) => ipcRenderer.invoke('chat:plan', payload),
  review: (payload) => ipcRenderer.invoke('chat:review', payload),
  reviewFix: (payload) => ipcRenderer.invoke('chat:reviewFix', payload),
  orchestrate: (payload) => ipcRenderer.invoke('chat:orchestrate', payload),
  missionStart: (payload) => ipcRenderer.invoke('mission:start', payload),
  missionGet: () => ipcRenderer.invoke('mission:get'),
  missionStop: () => ipcRenderer.invoke('mission:stop'),
  missionResume: (payload) => ipcRenderer.invoke('mission:resume', payload),
  exportChat: () => ipcRenderer.invoke('chat:export'),
  historyList: () => ipcRenderer.invoke('history:list'),
  historySave: (meta, conversation) => ipcRenderer.invoke('history:save', meta, conversation),
  historyLoad: (id) => ipcRenderer.invoke('history:load', id),
  historyDelete: (id) => ipcRenderer.invoke('history:delete', id),
  respondApproval: (id, approved) => ipcRenderer.send('approval:response', { id, approved }),
  respondQuestion: (id, answer) => ipcRenderer.send('question:response', { id, answer }),
  generateChatTitle: (conversationContent, model) => ipcRenderer.invoke('chat:generateTitle', conversationContent, model),
  toolsList: (mode) => ipcRenderer.invoke('tools:list', mode),

  onToken: (cb) => ipcRenderer.on('stream:token', (_e, t) => cb(t)),
  onThinking: (cb) => ipcRenderer.on('stream:thinking', (_e, t) => cb(t)),
  onCleanContent: (cb) => ipcRenderer.on('stream:cleancontent', (_e, t) => cb(t)),
  onInfo: (cb) => ipcRenderer.on('stream:info', (_e, t) => cb(t)),
  onState: (cb) => ipcRenderer.on('stream:state', (_e, t) => cb(t)),
  onSubagent: (cb) => ipcRenderer.on('stream:subagent', (_e, d) => cb(d)),
  onToolCall: (cb) => ipcRenderer.on('stream:toolcall', (_e, d) => cb(d)),
  onToolResult: (cb) => ipcRenderer.on('stream:toolresult', (_e, d) => cb(d)),
  onStats: (cb) => ipcRenderer.on('stream:stats', (_e, d) => cb(d)),
  onDone: (cb) => ipcRenderer.on('stream:done', () => cb()),
  onApprovalRequest: (cb) => ipcRenderer.on('approval:request', (_e, d) => cb(d)),
  onQuestionRequest: (cb) => ipcRenderer.on('question:request', (_e, d) => cb(d)),
  onMissionUpdate: (cb) => ipcRenderer.on('mission:update', (_e, mission) => cb(mission)),
});
