// Bridge between the UI (renderer) and main process. Keep this thin.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  listModels: () => ipcRenderer.invoke('models:list'),
  pickCwd: () => ipcRenderer.invoke('cwd:pick'),
  dirExists: (p) => ipcRenderer.invoke('dir:exists', p),
  send: (payload) => ipcRenderer.invoke('chat:send', payload),
  stop: () => ipcRenderer.send('chat:stop'),
  reset: () => ipcRenderer.invoke('chat:reset'),
  getConversation: () => ipcRenderer.invoke('chat:get'),
  loadConversation: (msgs, model) => ipcRenderer.invoke('chat:load', msgs, model),
  gitStatus: (cwd) => ipcRenderer.invoke('git:status', cwd),
  gitDiff: (cwd) => ipcRenderer.invoke('git:diff', cwd),
  gitGraph: (cwd) => ipcRenderer.invoke('git:graph', cwd),
  gitCommit: (cwd, message) => ipcRenderer.invoke('git:commit', cwd, message),
  memoryGet: (cwd) => ipcRenderer.invoke('memory:get', cwd),
  usageGet: () => ipcRenderer.invoke('usage:get'),
  isDev: () => ipcRenderer.invoke('app:isDev'),
  compact: (payload) => ipcRenderer.invoke('chat:compact', payload),
  loop: (payload) => ipcRenderer.invoke('chat:loop', payload),
  exportChat: () => ipcRenderer.invoke('chat:export'),
  historyList: () => ipcRenderer.invoke('history:list'),
  historySave: (meta, conversation) => ipcRenderer.invoke('history:save', meta, conversation),
  historyLoad: (id) => ipcRenderer.invoke('history:load', id),
  historyDelete: (id) => ipcRenderer.invoke('history:delete', id),
  respondApproval: (id, approved) => ipcRenderer.send('approval:response', { id, approved }),
  respondQuestion: (id, answer) => ipcRenderer.send('question:response', { id, answer }),
  generateChatTitle: (conversationContent, model) => ipcRenderer.invoke('chat:generateTitle', conversationContent, model),
  toolsList: () => ipcRenderer.invoke('tools:list'),

  onToken: (cb) => ipcRenderer.on('stream:token', (_e, t) => cb(t)),
  onThinking: (cb) => ipcRenderer.on('stream:thinking', (_e, t) => cb(t)),
  onCleanContent: (cb) => ipcRenderer.on('stream:cleancontent', (_e, t) => cb(t)),
  onInfo: (cb) => ipcRenderer.on('stream:info', (_e, t) => cb(t)),
  onState: (cb) => ipcRenderer.on('stream:state', (_e, t) => cb(t)),
  onSubagent: (cb) => ipcRenderer.on('stream:subagent', (_e, d) => cb(d)),
  onToolCall: (cb) => ipcRenderer.on('stream:toolcall', (_e, d) => cb(d)),
  onToolResult: (cb) => ipcRenderer.on('stream:toolresult', (_e, d) => cb(d)),
  onStats: (cb) => ipcRenderer.on('stream:stats', (_e, d) => cb(d)),
  onDone: (cb) => ipcRenderer.on('stream:done', () => cb()),
  onApprovalRequest: (cb) => ipcRenderer.on('approval:request', (_e, d) => cb(d)),
  onQuestionRequest: (cb) => ipcRenderer.on('question:request', (_e, d) => cb(d)),
});
